rich = Property.create(name: "rich")
poor = Property.create(name: "poor")
active = Property.create(name: "active")
inactive = Property.create(name: "inactive")
ps = Property.create(name: "ps")
solo = Property.create(name: "solo")
team = Property.create(name: "team")
online = Property.create(name: "online")
offline = Property.create(name: "offline")
handuse = Property.create(name: "handuse")
art = Property.create(name: "art")
mechanic = Property.create(name: "mechanic")
collecting = Property.create(name: "collecting")
gamble = Property.create(name: "gamble")
writing = Property.create(name: "writing")
competitive = Property.create(name: "competitive")
non_competitive = Property.create(name: "non_competitive")
observe = Property.create(name: "observe")
persistence = Property.create(name: "persistence")

rich.keywords.create(name: "wealthy")
rich.keywords.create(name: "rich")
rich.keywords.create(name: "costly")
rich.keywords.create(name: "expensive")

poor.keywords.create(name: "poor")
poor.keywords.create(name: "needless")
poor.keywords.create(name: "inexpensive")
poor.keywords.create(name: "cheep")

active.keywords.create(name: "active")
active.keywords.create(name: "dynamic")
active.keywords.create(name: "energetic")
active.keywords.create(name: "venture")

inactive.keywords.create(name: "passive")
inactive.keywords.create(name: "static")
inactive.keywords.create(name: "inactive")
inactive.keywords.create(name: "lazy")

ps.keywords.create(name: "strategy")
ps.keywords.create(name: "tactics")
ps.keywords.create(name: "ingenious")
ps.keywords.create(name: "logical")

solo.keywords.create(name: "alone")
solo.keywords.create(name: "himself")
solo.keywords.create(name: "solitary")
solo.keywords.create(name: "independent")

team.keywords.create(name: "together")
team.keywords.create(name: "cooperative")
team.keywords.create(name: "communicate")
team.keywords.create(name: "dependent")

online.keywords.create(name: "network")
online.keywords.create(name: "online")
online.keywords.create(name: "simulate")
online.keywords.create(name: "virtual")

offline.keywords.create(name: "offline")
offline.keywords.create(name: "reality")

handuse.keywords.create(name: "skill")
handuse.keywords.create(name: "craft")
handuse.keywords.create(name: "delicate")

art.keywords.create(name: "artistic")
art.keywords.create(name: "creative")
art.keywords.create(name: "aesthetic")

mechanic.keywords.create(name: "mechanical")
mechanic.keywords.create(name: "machine")
mechanic.keywords.create(name: "assemble")
mechanic.keywords.create(name: "structure")

collecting.keywords.create(name: "collect")
collecting.keywords.create(name: "limited")
collecting.keywords.create(name: "antique")
collecting.keywords.create(name: "rare")

gamble.keywords.create(name: "luck")
gamble.keywords.create(name: "gamble")
gamble.keywords.create(name: "risk")
gamble.keywords.create(name: "guess")

writing.keywords.create(name: "poem")
writing.keywords.create(name: "write")
writing.keywords.create(name: "collumn")

competitive.keywords.create(name: "fight")
competitive.keywords.create(name: "competitive")
competitive.keywords.create(name: "aggressive")
competitive.keywords.create(name: "battle")

non_competitive.keywords.create(name: "peaceful")
non_competitive.keywords.create(name: "sincere")
non_competitive.keywords.create(name: "relax")

observe.keywords.create(name: "watch")
observe.keywords.create(name: "see")
observe.keywords.create(name: "observe")
observe.keywords.create(name: "look")
observe.keywords.create(name: "view")

persistence.keywords.create(name: "persist")
persistence.keywords.create(name: "endure")
persistence.keywords.create(name: "patience")
